name: 'Create Argo App'
description: ''
author: 'Aharon Ohayon'

inputs:
    appName:
        description:
    services:
        descirption: 'The name of all the services to build'
        required: true

runs:
    using: 'node20'
    main: 'index.js'
