# This is a basic workflow to help you get started with Actions

name: main workflow

permissions:
  contents: write

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      stack:
        required: true
        type: string
      securityScan:
        required: true
        type: boolean

jobs:
  preperation:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.bumpServices.outputs.servicesToBuild }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Install Npm packages
        if: ${{ inputs.stack == 'nx' }}
        run: npm ci

      - name: Bump Services
        id: bumpServices
        uses: devcon-devops-as-a-service/actions/actions/bumpServices@main
        with:
          stack: ${{ inputs.stack }}

      - name: Echo Services output
        run: echo ${{ steps.bumpServices.outputs.servicesToBuild }}

  build-test-push:
    name: Build ${{ matrix.project }}
    needs: preperation
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.preperation.outputs.services) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Install Npm packages
        if: ${{ inputs.stack == 'nx' }}
        run: npm ci

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test Nx
        if: ${{ inputs.stack == 'nx' }}
        run: |
          npx nx test ${{ matrix.project }}

      - name: Build Docker Image
        run: docker build -f ${{ matrix.dockerfilePath }} . -t acrdeccondemo.azurecr.io/${{ matrix.project}}:${{ matrix.nextVersion }}

      - name: Push Docker Image to ACR
        run: |
          az acr login -n acrdeccondemo
          docker push acrdeccondemo.azurecr.io/${{ matrix.project}}:${{ matrix.nextVersion }}

      - name: Tag Service in git
        uses: devcon-devops-as-a-service/actions/actions/tagService@main
        with:
          service: ${{ matrix.project }}
          version: ${{ matrix.nextVersion }}

      - name: Run Microsoft Security DevOps
        if: ${{ inputs.securityScan }}
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          tools: trivy

  argoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: argocd cli installation
        run: |
          VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v$VERSION/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: check if app exists and create app if needed
        run: |
          argocd login 10.1.158.87 --username ${{ secrets.argouser }} --password ${{ secrets.argopassword }} 
          argocd app get ${{ inputs.appName }} &> /dev/null
          if [ $? -ne 0 ]; then
            echo "Application $APP_NAME does not exist. Deploying new application..."
            # Deploy the new application using application.yml
            argocd app create -f .././argocd/newapp.yml
          else
            echo "Application $APP_NAME already exists."
          fi
